name: project-ci
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      
      - name: Preparing base image for front end
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
        run: |
          FRONT_IMG_TAG=$(sha256sum package.json | cut -c1-15)
          RES=$(curl -u mdnfiras:$DOCKER_TOKEN https://registry.hub.docker.com/v2/repositories/mdnfiras/my-resume-base/tags | { grep $FRONT_IMG_TAG || true; } )
          if [ -z "$RES" ]; then
              echo "Did not find image with tag $FRONT_IMG_TAG"
              docker login -u mdnfiras -p $DOCKER_TOKEN
              docker build -f base.Dockerfile -t mdnfiras/my-resume-base:$FRONT_IMG_TAG .
              docker push mdnfiras/my-resume-base:$FRONT_IMG_TAG
              docker logout
          else
              echo "Found image with tag $FRONT_IMG_TAG"
          fi

      - name: Github pages
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          docker pull mdnfiras/my-resume:latest
          mkdir pages
          docker run -v $(pwd)/pages:/pages mdnfiras/my-resume:latest "/bin/bash -c 'cp -R /usr/share/nginx/html /pages'"
          ls pages
          cd pages
          pwd
