name: project-ci
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Preparing base image for front end
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}

        run: |
          FRONT_IMG_TAG=$(sha256sum package.json | cut -c1-15)
          echo $FRONT_IMG_TAG
          RES=$(curl -u mdnfiras:$DOCKER_TOKEN https://registry.hub.docker.com/v2/repositories/mdnfiras/my-angular-base/tags | grep $FRONT_IMG_TAG )
          echo "result is: $RES"
          docker --help
          if [ -z "$RES" ]; then
              echo "Did not find image with tag $FRONT_IMG_TAG"
              docker login -u mdnfiras -p $DOCKER_TOKEN
              docker build -f base.Dockerfile -t mdnfiras/my-angular-base:$FRONT_IMG_TAG .
              docker push mdnfiras/my-angular-base:$FRONT_IMG_TAG
          else
              echo "Found image with tag $FRONT_IMG_TAG"
          fi
