name: project-ci
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://node:16-alpine3.12
    steps:
      - uses: actions/checkout@v2
      - name: ci_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm install
          npm run ng build --output-path build
